### ISSUE TITLE
PR 리뷰: 9팀 리뷰했습니다~ 

### ISSUE THREAD

**Issue by hseoy** [woowa-techcamp-2021/cashbook-10#24]
- #12  리뷰 했습니다~~ ㅎㅎ [링크](https://github.com/woowa-techcamp-2021/cashbook-10/pull/12#pullrequestreview-718724423)

**Comment by CurlyBat** [comment]
- #12 저도 리뷰했습니다 [링크](https://github.com/woowa-techcamp-2021/cashbook-10/pull/12#discussion_r679654796)

**Comment by HobinLee** [comment]
감사합니다~! 덕분에 예상하지 못한 사이드 이펙트를 방지도 할 수 있게 되고 코드개선할 점이 보였네요~!
역시 갓윤서 갓윤관 부라더스... 다음에도 같이 리뷰합시다!!
