### ISSUE TITLE
[CSS] 수정 사항

### ISSUE THREAD

**Issue by HobinLee** [woowa-techcamp-2021/cashbook-10#55]
CSS수정 사항. 

1. 삭제 버튼 마우스 Hover 하지 않아도 나오게 변경하기 (max-width: 태블릿)
- [x] history-item
- [x] 헤더의 날짜 변경 버튼
- [x] detail-history에 날짜 변경 버튼
- [x] 스크롤 후, add button이 우측 하단에서 떨어짐
- [x] 데스크탑 모드일 때 add button 화면 우측하단이 아니라 page-content 우측 하단으로 위치했으면... 합니다... (헤더의 버튼들 처럼)

**Comment by kowoohyuk** [comment]
스크롤 후, add button이 우측 하단에서 떨어짐 => 시간 소요가 많을 거 같아 다른 부분 먼저 하겠습니다 😢
